(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var ListeMotsATrouver = /** @class */ (function () {
        function ListeMotsATrouver() {
        }
        ListeMotsATrouver.Liste = ['ASTHME', 'NARRATEUR', 'LASSITUDE', 'BATHILDE', 'VIOLON', 'PHOTOGRAPHIE', 'CHARDIN', 'LEONIE', 'REDINGOTE', 'AGRIGENTE', 'TILLEUL', 'GRASSET', 'CASERNE', 'CHAMBRE', 'STYLE', 'BRABANT', 'RIVEBELLE', 'NORPOIS', 'DECEPTION', 'LEGRANDIN', 'DACTYLO', 'PELISSE', 'RETROUVE', 'AMITIE', "PROUSTIFIER", 'INTELLIGENCE', 'COTTARD', 'PROMENADE', 'JUDAISME', 'VITRAIL', 'ECRITURE', 'BONTEMPS', 'GALLIMARD', 'INTERMITTENCE', 'DREYFUS', 'BERMA', 'INDIFFERENCE', 'PARME', 'FUGITIVE', 'CRUAUTE', 'ACTRICE', 'ANDREE', 'CATHEDRALE', 'JALOUSIE', 'MEDECINE', 'ORIANE', 'PASTICHE', 'MOREL', 'ESTHETIQUE', 'BABAL', 'SEVIGNE', 'BASIN', 'SNOBISME', 'RECHERCHE', 'AIME', 'LECTURE', 'TELEPHONE', 'PRISONNIERE', 'MONDAIN', 'FLAUBERT', 'COMTESSE', 'CONDORCET', 'AMOUR', 'FIGARO', 'GONCOURT', 'LOHENGRIN', 'DISPARUE', 'FORCHEVILLE', 'EGLISE', 'PROUST', 'ARISTOCRATIE', 'SOMMEIL', 'PLAGE', 'NEVROSE', 'PONCTUATION', 'AUBEPINE', 'MEDECINS', 'JEUNESSE', 'BALBEC', 'ALBARET', 'VENISE', 'BICYCLETTE', 'ROBERT', 'MADELEINE', 'BOTTINES', 'BOTTICELLI', 'PAPEROLLES', 'DONCIERES', 'MATINEE', 'LANTERNE', 'VOLONTE', 'AMIENS', 'INACHEVEMENT', 'BRICHOT', 'COCOTTE', 'LAUMES', 'JUPIEN', 'CATLEYA', 'ASPERGES', 'TEMPS', 'VINTEUIL', 'MARCEL', 'MEMOIRE', 'FRANCOISE', 'DISSERTATION', 'PHEDRE', 'INVERTI', 'ALBERTINE', 'MESEGLISE', 'COMBRAY', 'DOMESTIQUES', 'ADOLPHE', 'SANTEUIL', 'LILAS', 'TANSONVILLE', 'ANGOISSE', 'PARFUM', 'GUERMANTES', 'ODETTE', 'CULPABILITE', 'GILETIER', 'ELEGANCE', 'BOURDON', 'CAMBREMER', 'VILLEBON', 'IMPRESSION', 'MODERNITE', 'VILLEPARISIS', 'RACHEL', 'TELEGRAPHE', 'TANTE', 'CORRESPONDANCE', 'CHAMPI', 'RASPELIERE', 'TOURAINE', 'SENSATIONS', 'LIFTIER', 'AUTEUIL', 'FORTUNY', 'FAUBOURG', 'BERGOTTE', 'BIBLIOTHEQUE', 'MARQUISE', 'TISANE', 'TORTILLARD', 'MONTJOUVAIN', 'PRINCESSE', 'BOULOGNE', 'SONATE', 'RUSKIN', 'CHARLUS', 'DAUDET', 'ILLIERS', 'WAGNER', 'LEITMOTIV', 'ORANGEADE', 'LECTEUR', 'MONTESQUIOU', 'AUTOMOBILE', 'SWANN', 'LONGTEMPS', 'BALZAC', 'DEBUSSY', 'HABITUDE', 'DUCHESSE', 'OBSTACLE', 'GOMORRHE', 'THEATROPHONE', 'VERDURIN', 'ETYMOLOGIE', 'REMINISCENCE', 'DILETTANTE', 'PROFANATION', 'GILBERTE', 'ELSTIR', 'INCONSCIENT', 'SODOME', 'GIOTTO', 'BICHE', 'VIVONNE', 'ARPAJON', 'REYNALDO', 'PARIS', 'THEATRE', 'MAMAN', 'INSTINCT', 'PHRASE', 'PALAMEDE', 'MALADIE', 'ARBRES', 'AEROPLANE', 'BLOCH', 'SIMONET', 'INVERSION'];
        return ListeMotsATrouver;
    }());
    exports.default = ListeMotsATrouver;
});
//# sourceMappingURL=listeMotsATrouver.js.map